name: Quick Check
on:
  push:
    branches: ['**']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.claude/**'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.claude/**'
      - 'LICENSE'
      - '.gitignore'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  quick-check:
    name: Quick Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Fail if takes longer than 5 minutes
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-quick-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-quick-
            ${{ runner.os }}-cargo-
      
      # Format check - should be instant
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      # Clippy with strict rules - ~30 seconds with cache
      - name: Clippy strict
        run: cargo clippy --all-targets -- -D warnings
      
      # Quick compile check - ~30 seconds with cache  
      - name: Compile check
        run: cargo check --all-features
      
      # Skip doc check in quick-check - it's too slow (1m 44s)
      # Doc checking moved to full-test suite
      
      # Skip tests in quick-check - cargo check is sufficient
      # Tests moved to full-test suite